var q=null;function r(c){return function(j){this[c]=j}}
(function(c){function j(a,b){var c,d=[],e,h,l,p;if(!(a=s(a)))return q;if("undefined"==typeof b)b=document;else if(b=m(b),!b)return d;c&&(c=s(c).toUpperCase());if(b.getElementsByClassName){l=b.getElementsByClassName(a);e=l.length;for(h=0;h<e;h++)p=l[h],c&&p.tagName!=c||(d[d.length]=p)}else{a=RegExp("(^|\\s)"+a+"(\\s|$)");l=c?b.getElementsByTagName(c):b.all||b.getElementsByTagName("*");e=l.length;for(h=0;h<e;h++)p=l[h],a.test(p.className)&&(d[d.length]=p)}return d}function m(a){if("string"==typeof a||
a instanceof String)return document.getElementById(a);else if(a&&a.nodeName&&(a.nodeType==1||a.nodeType==9))return a;return q}function u(){if(c&&(c.ca.prototype.La=function(){this.i.className="main";c.f.show(this.i);this.G=!0;this.g=-1},!window.Yb))aa=new c.ca(!1,"headq","aa","http://tip.soku.com/search_keys"),aa.Nb("&site=2"),aa.Lb("/search_video/q_"),aa.Jb("http://lstat.youku.com"),aa.Mb("http://www.soku.com"),aa.Kb(!0),aa.suggestUpdate=aa.Oa}window.nova_init_hook_searchinputinit=function(){u()};
c.global=window;var s=String.prototype.trim?function(a){return a==q?"":String.prototype.trim.call(a)}:function(a){return a==q?"":a.toString().replace(/^[\s\xA0]+/,"").replace(/[\s\xA0]+$/,"")};c.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};c.bind=function(a,b){var c=arguments.length>2?Array.prototype.slice.call(arguments,2):q;return function(){var d="[object String]"==Object.prototype.toString.call(a)?b[a]:a,e=c?c.concat(Array.prototype.slice.call(arguments,0)):arguments;
return d.apply(b||d,e)}};c.e={element:function(a){return a.target||a.srcElement},h:function(a,b,c,d){if(b=="keypress"&&(navigator.appVersion.match(/Konqueror|Safari|KHTML/)||a.attachEvent))b="keydown";a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&(a["e"+b+c]=c,a[b+c]=function(){return a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c]))}};c.f={lc:function(a){return m(a).style.display!="none"},n:function(){for(var a=0;a<arguments.length;a++)m(arguments[a]).style.display="none"},show:function(){for(var a=
0;a<arguments.length;a++)m(arguments[a]).style.display="block"},ac:function(a){a=m(a);return a.offsetHeight},T:function(a,b){if(a=m(a))a.className=""==a.className?b:a.className+" "+b},Z:function(a,b){if(a=m(a))a.className=a.className.replace(RegExp("(^| )"+b+"( |$)"),"$1").replace(/ $/,"")},ia:function(a,b,c){var d=b;if(typeof b==="string")if(c===void 0)return a&&a.getAttribute(b);else d={},d[b]=c;for(var e in d)a.setAttribute(e,d[e])}};c.fb={Sa:8,ib:9,bb:13,Wa:27,Za:37,jb:38,cb:39,Ua:40,Ub:46,ab:33,
$a:34,Va:35,Xa:36,Ya:45,eb:16,Ta:17,Ra:18};c.ca=function(a,b,f,d){a||c.e.h(document,"click",c.bind(this.Aa,this));c.e.h(document,"blur",c.bind(this.Aa,this));this.ha={};this.Ha=this.pb;if(f)this.Ha=f;this.Y=navigator&&navigator.userAgent.toLowerCase().indexOf("msie")!=-1;this.b=document.getElementById(b);c.e.h(this.b,"keypress",c.bind(this.onkeydown,this));var e=this;this.w=c.global.VideoWall;this.ya=0;this.b.onblur=function(){a&&VideoWall&&VideoWall.show();e.n()};a?c.e.h(this.b,"focus",c.bind(this.focus,
this)):c.e.h(this.b,"dblclick",c.bind(this.lb,this));this.count=0;this.qa=this.xa;this.Na=this.hb;if(d)this.qa=d;this.Ma="";this.Ea=this.xa;this.Fa=this.gb;this.$=this.ob;this.Ka=this.nb;this.bc="";this.Ab=this.mb+this.fa;this.ka=this.L=!0;this.i=document.createElement("div");this.i.style.display="none";this.C=document.createElement("div");this.C.className="kubox";this.C.id="kubox";this.b.parentNode.appendChild(this.C);this.F=document.createElement("iframe");this.F.frameBorder=0;this.F.scrolling=
"no";this.F.style.position="absolute";this.F.style.top="-1px";this.F.style.left="-1px";this.C.appendChild(this.F);this.C.appendChild(this.i);this.V=document.createElement("div");this.V.className="panels";this.ua=document.createElement("div");this.ua.className="all";this.C.appendChild(this.ua);this.A=document.createElement("div");this.G=!1;this.K=this.D="";if(this.b&&this.b.value!="")this.K=this.b.value;this.I=this.K;this.ba=!1;this.la=!0;this.S=-1;this.W=this.Zb=0;if(a)this.s=document.getElementById("canplay"),
c.e.h(this.s,"mouseover",c.bind(this.na,this)),c.f.n(this.s);this.ma=a;window.onresize=c.bind(this.Sb,this);this.N();this.oa=2;if(this.b)this.M=setTimeout(c.bind(this.pa,this),this.ga)};c.extend(c.ca.prototype,{start:function(){this.M!=0&&clearTimeout(this.M);this.M=setTimeout(c.bind(this.pa,this),this.ga);if(this.b&&this.b.value!="")this.I=this.K=this.b.value},dc:r("oa"),gc:r("w"),ec:r("Ha"),fc:function(a,b){this.qa=a;if(b)this.Na=b;this.N()},Nb:r("Ma"),Jb:function(a,b){this.Ea=a;if(b)this.Fa=b},
Mb:r("$"),cc:function(a){this.Ab=a.indexOf(this.fa)>0?a:a+this.fa},Kb:r("Ia"),Lb:r("Ka"),ub:function(a){return encodeURI(this.$+this.Ka+a)},vb:function(a){return encodeURI(this.qa+this.Na+a+this.Ma+this.wb())},H:function(a,b,f,d){if(c.global.sokuClickStat){var e={};e._log_type=a;e._log_site=this.oa;e._log_pos=b;e.keyword=f;d||(d=c.global.location.href);e._log_url=d;c.global.sokuClickStat(e)}else e="",a&&(e+=a),b&&(e+="&pos="+b),f&&(e+="&keyword="+f),d||(d=c.global.location.href),d&&(e+="&url="+encodeURIComponent(d)),
(new Image).src=encodeURI(this.Ea+this.Fa+e+"&site="+this.oa+"&rand"+Math.round(Math.random()*2147483647))},Ib:function(){var a=this;this.b.onblur=function(){a.ma&&a.w&&a.w.show();a.n()}},lb:function(){if(this.b.createTextRange){var a=this.b.createTextRange();a.moveStart("character",0);a.select()}else this.b.setSelectionRange&&this.b.setSelectionRange(0,this.b.value.length);this.L&&this.b.value!=""&&(this.D==this.b.value?this.i.innerHTML!=""&&this.show():this.O())},focus:function(){this.Ib();this.ma&&
(navigator.userAgent.match(/msie/i)?this.ya>0&&this.w&&this.w.hide():this.w&&this.w.hide());this.ya++;this.L&&this.la&&this.b.value!=""&&(this.D==this.b.value?this.i.innerHTML!=""&&this.show():this.O())},aa:function(){return this.S!=-1},Sb:function(){this.G&&this.show()},onkeydown:function(a){this.ma&&this.w&&this.w.hide();if(a.ctrlKey)return!0;var b=c.fb;switch(a.keyCode){case b.ab:case b.$a:case b.Va:case b.Xa:case b.Ya:case b.Ta:case b.Ra:case b.Za:if(this.aa())this.S=-1,this.P();return!0;case b.cb:if(a=
document.getElementById("ddiv"+this.g))return this.wa=j("item",a),this.W=this.wa.length,this.S=this.g,this.o=0,this.R(),!0;a=this.z(this.B(),this.ea);b=this.z(this.B(),this.v);if(a&&a.length>0)return this.H(4,3,b,a),window.open(a,"video"),!1;return!0;case b.eb:case b.ib:return!0;case b.Wa:return this.la=!1,this.n(),!1;case b.jb:if(this.G)this.aa()?this.zb():(this.ba=!0,this.Ob());else{if(this.i.childNodes.length>1&&this.D==this.b.value&&this.L)return this.show(),!1;this.b.value!=""&&this.O()}this.Y?
a.returnValue=!1:a.preventDefault();return!1;case b.Ua:if(this.G)this.aa()?this.yb():(this.ba=!0,this.qb());else{if(this.i.childNodes.length>1&&this.D==this.b.value&&this.L)return this.show(),!1;this.b.value!=""&&this.O()}this.Y?a.returnValue=!1:a.preventDefault();return!1;case b.bb:if(this.aa())return b=this.z(this.B(),this.v),this.H(4,2,b,this.va),window.open(this.va,"_blank"),this.Y?a.returnValue=!1:a.preventDefault(),!1;if(this.G&&this.g>-1&&!this.select())return this.Y?a.returnValue=!1:a.preventDefault(),
!1;case b.Sa:if(this.b.value.length==1)this.I="";default:return this.ba=!1,!0}},pa:function(){if(!(document.activeElement&&document.activeElement!=this.b))if(this.b.value!=""&&this.b.value!=this.K)this.D!=this.b.value&&(this.ba||this.O());else if(this.D!="")this.D="",this.G&&(this.n(),this.N());this.b.value==""&&this.s&&c.f.n(this.s);this.M!=0&&clearTimeout(this.M);this.M=setTimeout(c.bind(this.pa,this),this.ga)},Ca:function(a,b,c){c.stopPropagation?c.stopPropagation():c.cancelBubble=!0;this.H(4,
3,a,b)},Qa:function(a,b){this.H(4,2,a,b)},Rb:function(a,b){this.H(4,3,a,b)},Qb:function(a,b){this.H(5,1,a,b)},select:function(a){if(this.B()){this.B().getAttribute(this.sa);var b=this.z(this.B(),this.v);try{if(a){if(this.I=b,!this.Ia)this.b.value=b}else{if(this.b.value!=b)return!0;this.I=b;b=this.b.value}this.H(4,1,b);this.n();var c=this.ub(b);this.Ia?window.open(c,"_blank"):document.location=c}catch(d){}}return!1},O:function(){if(this.L){this.K="";var a=this.b.value;this.D=this.I=a;this.ha[a]?this.Oa(this.ha[a]):
a.length>22||this.sb(this.vb(a),a)}},N:function(){this.size=0;this.g=-1;this.i.innerHTML="";this.A.innerHTML=""},Hb:function(){setTimeout(c.bind(this.Pb,this),5)},Ba:function(a){return a.nodeType==1},X:function(a){if(a&&a.getElementsByTagName("div").length>0)return this.z(a.getElementsByTagName("div")[0],this.ta);return q},z:function(a,b){if(a&&a.getAttribute(b))return this.unescape(a.getAttribute(b))},Pb:function(){this.kb();var a=this.b.value;if(this.A.innerHTML=="")this.i.innerHTML!=""&&this.X(this.i)==
a||(this.n(),this.N());else if(this.X(this.A)!=a&&a!="")this.i.innerHTML!=""&&this.X(this.i)==a||this.n();else{for(var b,f=!1,d=this.A.getElementsByTagName("div")[0].getElementsByTagName("li"),a=0;a<d.length;a++)if(b=d[a],this.Ba(b)){f=!0;break}if(f){this.i.innerHTML=this.A.innerHTML;d=this.i.getElementsByTagName("div")[0].getElementsByTagName("li");this.size=0;this.U=[];for(a=0;a<d.length;a++)if(b=d[a],this.Ba(b)){b.setAttribute(this.da,this.size);c.e.h(b,"mousemove",c.bind(this.Db,this));c.e.h(b,
"mouseover",c.bind(this.Ga,this));c.e.h(b,"mouseout",c.bind(this.Fb,this));c.e.h(b,"click",c.bind(this.select,this));var e=b.getElementsByTagName("a"),f=this.z(b,this.v);e[0]&&c.e.h(e[0],"click",c.bind(this.Ca,this,f,e[0].href),!0);e[1]&&c.e.h(e[1],"click",c.bind(this.Ca,this,f,e[0].href),!0);this.U.push(b);this.size++}this.show();this.ja=!1;for(a=b=0;a<10;a++)if(f=document.getElementById("ddiv"+a)){c.e.h(f,"mouseover",c.bind(this.na,this));c.e.h(f,"mouseout",c.bind(this.Ja,this));d=j("item",f);b+=
d.length;f.style.height="300px";if(f.attachEvent)for(e=0;e<d.length;e++)c.e.h(d[e],"mouseenter",c.bind(this.Bb,this)),c.e.h(d[e],"mouseleave",c.bind(this.Cb,this));else for(e=0;e<d.length;e++)c.e.h(d[e],"mouseover",c.bind(this.Gb,this)),c.e.h(d[e],"mouseout",c.bind(this.Eb,this));f=this.z(f,"itemq");for(e=0;e<d.length;e++){var h=j("title",d[e]),l=j("thumb",d[e]),p=h[0].getElementsByTagName("a")[0].href;h&&(c.e.h(h[0].getElementsByTagName("a")[0],"click",c.bind(this.Qa,this,f,p)),c.e.h(l[0].getElementsByTagName("img")[0],
"click",c.bind(this.Qa,this,f,p)));(h=j("play",d[e]))&&h[0].getElementsByTagName("a").length&&c.e.h(h[0].getElementsByTagName("a")[0],"click",c.bind(this.Rb,this,f,h[0].getElementsByTagName("a")[0].href))}}j("main",this.C)[0].style.height=b>0?"299px":"";if(a=m("ddiv0"))c.f.show(a),c.f.show(a.parentNode),this.Da(a)}else this.n(),this.N();this.F.style.width="385px";this.F.style.height=this.C.offsetHeight+"px"}},La:function(){c.f.show(this.i);this.G=!0;this.g=-1},show:function(){c.f.show(m("kubox"));
this.i.childNodes.length<1||(!this.L||!(this.b.value!=""&&this.X(this.i)!=this.b.value))&&this.La()},n:function(){this.J();c.f.n(this.i);c.f.n(m("kubox"));this.g=-1;this.G=!1},Aa:function(){if(this.ka)this.n(),this.ka=!1,setTimeout(c.bind(this.rb,this),60)},rb:function(){this.ka=!0},Db:function(a){this.ja=!0;this.Ga(a)},Ga:function(a){this.na();if(this.ja){for(a=c.e.element(a);a.parentNode&&(!a.tagName||a.getAttribute(this.da)==q);)a=a.parentNode;a=a.tagName?a.getAttribute(this.da):-1;if(!(a==-1||
a==this.g))this.J(),this.g=Number(a),this.Q(!1)}else this.ja=!0},Fb:function(){this.J();this.g=-1;this.Ja()},tb:function(a){if(this.U&&a>=0&&a<this.U.length)return this.U[a]},B:function(){return this.tb(this.g)},xb:function(a,b){if(!a)this.b.value=b},Da:function(a){for(var a=a.getElementsByTagName("img"),b=0;b<a.length;b++)a[b].setAttribute("src",a[b].getAttribute("_src"))},Q:function(a){var b=this.B(),f;if(b){c.f.T(b,this.ra);try{f=this.z(b,this.v);this.xb(!a,f);var d=this.z(b,this.ea);a&&this.Pa(d)}catch(e){}}for(a=
0;a<10;a++)if(f=m("ddiv"+a))if(a==this.g){c.f.show(f);c.f.show(f.parentNode);this.Da(f);b=289-f.getAttribute("itemC")*90;f=f.getElementsByTagName("div");for(d=0;d<f.length;d++)if(f[d]&&f[d].className&&f[d].className=="item"){var h=this.g;f[d].style.top=(h*28>b?b:h*28)+"px"}}else this.S=-1,c.f.n(f)},J:function(){var a=this.B();a&&c.f.Z(a,this.ra)},Ob:function(){var a=this.g;this.g>0?(this.J(),this.g=a-1,this.Q(!0)):this.g==0?(this.J(),this.g=a-1,this.b.value=this.I):(this.g=this.size-1,this.Q(!0))},
qb:function(){var a=this.g;this.g<0?(this.g=a+1,this.Q(!0)):this.g<this.size-1?(this.J(),this.g=a+1,this.Q(!0)):(this.J(),this.g=-1,this.b.value=this.I)},zb:function(){var a=this.o;if(this.o>0)this.P(),this.o=a-1,this.R();else if(this.o==0)this.P(),this.o=this.W-1,this.R()},yb:function(){var a=this.o;if(this.o<this.W-1)this.P(),this.o=a+1,this.R();else if(this.o==this.W-1)this.P(),this.o=0,this.R()},za:function(){return this.wa[this.o]},R:function(){var a=this.za();this.va=j("title",a)[0].getElementsByTagName("a")[0].href;
c.f.T(a,"current")},P:function(){c.f.Z(this.za(),"current")},Gb:function(a){for(a=c.e.element(a);a&&a.nodeName!="BODY";)a=a.parentNode,a.className=="item"&&c.f.T(a,"current")},Eb:function(a){for(var b=c.e.element(a);b&&b.nodeName!="BODY";)if(b=b.parentNode,b.className.indexOf("item")>-1)break;(a.relatedTarget?a.relatedTarget:a.toElement)==b&&c.f.Z(b,"current")},Bb:function(a){a=c.e.element(a);c.f.T(a,"current")},Cb:function(a){a=c.e.element(a);c.f.Z(a,"current")},kb:function(){var a=document.getElementById("soku_autocomplete");
a&&a.tagName.toUpperCase()=="SCRIPT"&&a.parentNode.removeChild(a)},sb:function(a){var b=document.createElement("script");b.src=a;b.id="soku_autocomplete";document.getElementsByTagName("HEAD")[0].appendChild(b)},unescape:function(a){return a.replace(RegExp("&quot;","gm"),'"').replace(RegExp("&gt;","gm"),">").replace(RegExp("&lt;","gm"),"<").replace(RegExp("&amp;","gm"),"&")},escape:function(a){return a.replace(RegExp("&","gm"),"&amp;").replace(RegExp("<","gm"),"&lt;").replace(RegExp(">","gm"),"&gt;").replace(RegExp('"',
"gm"),"&quot;")},hc:function(a){if(a.length<=43)return a;return a.substr(a,40)+"..."},Oa:function(a){this.la=!0;this.V.innerHTML="";this.A.innerHTML="";this.S=-1;if(a&&typeof a==="object"){var b=a.q;this.ha[b]=a;this.Pa(a.p);if((a=a.r)&&a.length){var f=document.createElement("div");f.setAttribute(this.ta,this.escape(b));for(var d=document.createElement("ul"),e=document.createElement("ul"),h=0,l=0,m=a.length;l<m;l++){var n=a[l],i=document.createElement("li"),h=n.c;J=0;var g=this.escape(h),j=g;n.t&&
(J=n.t);var h=n.d,o=s(b);g!=o&&g.indexOf(o)>-1&&(g=o+'<b style="font-weight:bold">'+g.substring(g.indexOf(o)+o.length)+"</b>");i.setAttribute(this.sa,J);if(J==0)h==1&&(g+="<span class='expand'>&gt;</span>"),i.innerHTML=g,c.f.ia(i,{"class":""}),d.appendChild(i),g=j.replace(/^\d+\. /,""),i.setAttribute(this.v,g),d.setAttribute(this.v,g);else if(J==1)i.setAttribute(this.v,j),i.setAttribute(this.ea,this.escape(n.l)),g+="<a class='goplay' target='_blank' href='"+this.escape(n.l)+"'><em>\u64ad\u653e</em></a>",
i.innerHTML=g,c.f.ia(i,{"class":""}),d.appendChild(i),j=j.replace(/^\d+. /,""),d.setAttribute(this.v,j);if(h==1){i=document.createElement("div");g=[];n=n.u;for(o=0;o<n.length;o++){var k=n[o],t=k.k;k.d.indexOf("detail")!=-1&&k.d.indexOf("www.soku.com")==-1&&this.$&&(k.d=this.$+k.d);g.push("<div class='item' itemindex='"+o+"'>");g.push("<div class='thumb'><a target='_blank' href='");g.push(k.d);g.push("'><img _src='");g.push(k.a);g.push("' /></a></div>");g.push("<div class='title'><a target='_blank' href='");
g.push(k.d);g.push("'>");g.push(k.j+"</a></div>");g.push("<div class='pub'>");g.push(k.m);g.push(" ");g.push(k.y);g.push("</div>");g.push("<div class='actor'>");k.p&&k.p.length&&g.push(k.p);g.push("</div>");g.push("<div class='play'>");t&&t.length&&(g.push("<a target='_blank' href='"),g.push(t),g.push("'><em>\u64ad\u653e</em></a>"));g.push("</div>");g.push("</div>")}i.innerHTML=g.join("");i.setAttribute("id","ddiv"+l);i.setAttribute("itemC",n.length);i.setAttribute("itemq",j);i.className="panel";
this.V.appendChild(i)}c.f.ia(d,{"class":"autolist"});f.appendChild(d);h==1&&f.appendChild(e);this.A.appendChild(f);this.A.appendChild(this.V)}}}this.Hb()},kc:function(){},Pa:function(a){if(this.s)if(a&&a.length>0){c.f.show(this.s);this.s.innerHTML="<a target='_blank' href='"+a+"'><em>\u64ad\u653e</em></a>";var a=this.s.getElementsByTagName("a"),b=this.b.value,f=a.href;a&&c.e.h(a[0],"click",c.bind(this.Qb,this,b,f))}else c.f.n(this.s),this.s.innerHTML=""},$b:function(){this.b.focus();if(this.b.createTextRange){var a=
this.b.createTextRange();a.moveStart("character",this.b.value.length);a.select()}else this.b.setSelectionRange&&this.b.setSelectionRange(this.b.value.length,this.b.value.length)},na:function(){this.b.onblur=q},Ja:function(){this.b.onblur=c.bind(this.n,this)},jc:function(){return"&time="+new Date},wb:function(){return"&h="+(new Date).getHours()},Xb:"mouseSelect",Wb:"keySelect",Vb:"iconPress",Tb:"changeStatus",ga:50,da:"autoindex",ra:"current",sa:"hitt",v:"hitq",ea:"hitl",ta:"squery",fa:".suggest",
hb:"?query=",gb:"/sokuClick.php?type=",xa:"http://"+location.host+"/suggest/",ob:"http://"+document.domain+"/search?",nb:"/v?keyword=",mb:document.domain.replace(/.soku.com/,""),pb:"aa",ic:"SUG_STATUS"})})({});
