
try{document.domain="56.com";}catch(e){}
function $_(ele){return document.getElementById(ele);}
function jLoader(source,autoRemove,id,charset){id=id||"";charset=charset||"gb2312";autoRemove=autoRemove||false;var b=document.getElementsByTagName("head")[0];var c=document.createElement("script");c.type="text/javascript";c.charset=charset;if(id){c.id=id;}
c.src=source;var remove=function(){c.onload=null;var h=c.parentNode;h.removeChild(c);delete c;};var e=function(h){var j=(h?h:window.event).target?(h?h:window.event).target:(h?h:window.event).srcElement;if(j.readyState=="loaded"||j.readyState=="complete"){j.onreadystatechange=null;if(autoRemove){remove();}}};if(navigator.product=="Gecko"&&autoRemove){c.onload=remove;}else{c.onreadystatechange=e;}
b.appendChild(c);}
function setStat(s,t){var u="http://stat3.corp.v-56.com/player.htm?s=";t=t||false;if(t==true){jLoader(u+s,true);}else{setTimeout(function(){jLoader(u+s,true);},1000);}}
var _={"map":function(vars,func){func(vars);},"rand":function(begin,end){if(typeof begin!='undefined'){end=end?end:2147483648;return Math.floor(Math.random()*(end-begin)+begin);}else{a=new Date();return a.getTime();}},"r":function(vars){eval(vars);},"mbox":function(){var url='http://msg.56.com/getnewmsgforadmin.php?user='+usr.gLoginUser()+'&callback=_h.mboxnum';jLoader(url);},"e":function(){var elements=[];for(var i=0;i<arguments.length;i++){var element=arguments[i];if(typeof element=='string')element=document.getElementById(element);if(arguments.length==1)return element;elements.push(element);}
return elements;},"get":function(name){var get=location.search||location.hash;var start=get.indexOf(name+'=');if(start==-1)return'';var len=start+name.length+1;var end=get.indexOf('&',len);if(end==-1)end=get.length;return unescape(get.substring(len,end));},"setCookie":function(name,value,hours,domain){var options={};if(hours){options.expires=hours;}
if(domain){options.domain=domain;options.path="\/";}
if(name=="view_rec"||name=="quicklist"||name=="quicklistTuto"){jQuery_cookie(name,value,options);}},getCookieVal:function(offset){var endstr=document.cookie.indexOf(";",offset);if(endstr==-1){endstr=document.cookie.length;}
return unescape(document.cookie.substring(offset,endstr));},getCookie:function(name){var arg=name+"=";var alen=arg.length;var clen=document.cookie.length;var i=0;while(i<clen){var j=i+alen;if(document.cookie.substring(i,j)==arg){return this.getCookieVal(j);}
i=document.cookie.indexOf(" ",i)+1;if(i==0)break;}
return"";},getUserid:function(){var user=this.getCookie("member_id");return user.substring(0,user.indexOf("@"));}};var usr={"gLoginId":function(){return(_.getCookie("member_id"));},"user_nick":function(){return((decodeURIComponent&&_.getCookie("user_nickname_js").length)?decodeURIComponent(_.getCookie("user_nickname_js")):_.getUserid());},"gLoginPass":function(){return(_.getCookie("pass_hex"));},"gLoginUser":function(){var uid=typeof(this.gLoginId)=='function'?this.gLoginId():this.gLoginId;return(uid.indexOf("@")==-1?uid:uid.substring(0,uid.indexOf("@")));},"user_id":function(){return this.gLoginUser();},"photo":function(u,b){var a1=0,a2=0,i,rs;u=u||this.gLoginUser();for(i=0;i<u.length;i++){a1+=u.charCodeAt(i)*i;a2+=u.charCodeAt(i)*(i*2+1);}
a1%=100;a2%=100;rs='http://uface.56.com/photo/'+a1+"/"+a2+"/";if(b){return rs+u+"_b_56.com_.jpg";}else{return rs+u+"_56.com_.jpg";}},"gIsLogin":function(){return(_.getCookie("member_id")!=""&&_.getCookie("pass_hex")!="")?true:false;},"gIsHomepage":function(){var gh=window.location.host;if(gh=='www.56.com'||gh=='56.com'){return true;}else{return false;}}};var _h={HeaderNav:function(id){var a=[(usr.gIsLogin()?'<li>您好, <a href="http://'+usr.gLoginUser()+'.56.com/" target="_blank">'+(usr.user_nick().length>=12?usr.user_nick().substring(0,14)+'..':usr.user_nick())+'</a></li><li><a href="http://www.56.com/admin/" onclick="setStat(\'i_nav_center\');" target="_blank">个人中心</a></li><li class="last"><a target="_self" href="http://urs.56.com/php/logout.php">退出</a></li>':'<li>你好, 请<a href="javascript:login();">登录</a></li><li class="last"><a href="http://user.56.com/reg/" target="_blank">注册</a></li>')];$_(id).innerHTML=a;},mboxnum:function(data){if(data.total>0){var html='(<span class="red">'+data.total+'</span>)';$_("mboxid").innerHTML=html;}},csubstr:function(str,s,e){var r='';if(typeof(str)!='string'){return str;}
var l=str.length;if(e>l*2){return str;}
for(var i=0;i<l;i++){if(s>i)continue;if(str.charCodeAt(i)>255){if(e==1){return r;}
e=e-2;}else{e--;}
if(str.charAt(i)==undefined){return r;}
r=r+str.charAt(i);if(e<=0){return r;}}
return r;},checkselect:function(dio){for(i=0;i<dio.length;i++){if(dio[i].selected){return dio[i].value;}}
return false;},getNotice:function(){var l=_.getCookie("cityname");var ele=usr.gIsLogin()?'dd':'p';return'<'+ele+' class="login_tips">友情提示：支持原创,请勿上传未经授权的作品！</'+ele+'>';},indexLogin:function(id){_.e('h_info_div').innerHTML=a_h_b.userStatus();},getUnLoginStr:function(){var loginStr='<div class="title">';if($.browser.msie){loginStr+='<span class="side"><a id="sethomepage" style="" href="javascript:_h.onhomepage();" class="last">把56设为首页</a></span>';}
loginStr+='<h2>欢迎登录56网！</h2>';loginStr+='</div>';loginStr+='<div class="content">';loginStr+='<form target="add_favorite" id="loginForm" name="loginForm" method="post" action="http://www.renren.com/t-signin2">';loginStr+='<p class="tips"><span id="login_tips" class="warning"></span></p>';loginStr+='<p><label for="username">用户名：</label>';loginStr+='<input type="text" size="24" class="userpass" id="username" name="e" onblur="checkUserSafeStatus()"/>';loginStr+='</p>';loginStr+='<p>';loginStr+='<label for="password">密　码：</label><input type="password" size="24" class="userpass" id="password" name="p" onKeyDown="if(event.keyCode==13){fCheck();}"/>';loginStr+='<a name="forget" class="forget" target="_blank" href="http://www.56.com/help/profile/password.html">忘记密码？</a>';loginStr+='</p>';loginStr+='<p id="serialStyle" style="display:none">';loginStr+='<label for="verifycode">验证码：</label>';loginStr+='<input id="txtVerify" class="userpass" type="text" maxlength="4" value="输入下图的字符"  onclick="this.value=\'\';" size="24" name="icode">';loginStr+='<img class="verify_img" style="display:inline-block;"  id="serialImg_login" name="serialImg" onclick="changePic(\'56_login\')" src="http://icode.renren.com/getcode.do?t=56_login&rnd="> <a href="javascript:;changePic(\'56_login\')"><u>看不清，换一张</u></a>';loginStr+='</p>';loginStr+='<input type="hidden" value="56_login" name="captcha_type">';loginStr+='<input type="hidden" value="56.com" name="d">';loginStr+='<input type="hidden" name="u" value="http://www.56.com/admin/|http://www.56.com/js/login/login_box_error_v_3.html" />';loginStr+='<input type="hidden" value="true" name="autoLogin"/>';loginStr+='<p class="btn"><input type="button" class="btn_login" onclick="fCheck()" value=" 登 录 "/>';loginStr+='<a class="reg" onclick="setStat(\'i_nav_reg\');" target="_blank" href="http://user.56.com/reg/">免费注册</a></p>';loginStr+='<p class="app_login">';loginStr+=weibo.getHomeIcon();loginStr+='</p>';loginStr+='<p>已绑定人人网帐号，请用人人网帐号登录</p>';loginStr+='</form></div>';return loginStr;},onhomepage:function(){var pageURL='http://www.56.com';if(document.documentElement.doScroll){document.body.style.behavior='url(#default#homepage)';document.body.setHomePage(pageURL);}else{if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");}catch(e){alert("该操作被浏览器拒绝，如果想启用该功能，请在地址栏内输入 about:config,然后将项signed.applets.codebase_principal_support 值该为true");}}
var prefs=Components.classes['@mozilla.org/preferences-service;1'].getService(Components.interfaces.nsIPrefBranch);prefs.setCharPref('browser.startup.homepage',pageURL);}},calllikemsg:false,show_likevideo:function(data){var tdata=data.data;var length=tdata.length;var html='';var cl='';if(tdata!=' '&&tdata!=undefined&&length>0){this.calllikemsg=true;html='<ul class="v_list">';for(var i in tdata){if(i==2||i==5)cl=' class="last"';html+='<li'+cl+'>';html+='<a onmousedown="setStat(\'ua_like\',1000)" title="'+tdata[i].Subject+'" class="img" href="'+tdata[i].url+'" target="_blank"><img alt="'+tdata[i].Subject+'" src="'+tdata[i].img+'">'+_h.csubstr(tdata[i].Subject,0,14)+'</a>';html+='<span class="ply"><s title="播放"></s>'+tdata[i].times+'</span>';html+='</li>';cl='';if(i==5)break;}
html+='</ul>';$_("none_mylike").style.display="";$_("mylikecontent").innerHTML=html;}else{$_("none_mylike").style.display="none";}
$_("may_like_box").className='sbox may_like box_open';},showmorelikeList:function(){var url='http://msg.ua.56.com/api/maybelike.php?&more=1&callback=_h.show_likevideo';jLoader(url,'','','utf8');},showlikeList:function(){var likehtml='';if(usr.gIsLogin()||_.getCookie('uaid')){likehtml+='<div class="sbox may_like box_close" id="may_like_box">';likehtml+='<span class="side">';likehtml+='<a title="更多您可能喜欢的视频" href="javascript:_h.showmorelikeList();">更多</a>';likehtml+='</span>';likehtml+='<div onmousedown="_h.initlikeList(0);" class="title">';likehtml+='<div class="starus"><a class="o_exp" href="javascript:;">0</a></div>';likehtml+='<h2>您可能喜欢的</h2>';likehtml+='</div>';likehtml+='<div class="content" id="mylikecontent"></div>';likehtml+='</div>';$_("none_mylike").innerHTML=likehtml;this.initlikeList();}else{$_("none_mylike").style.display="none";}},initlikeList:function(t){if($_("may_like_box").className=='sbox may_like box_close'&&this.calllikemsg==false){var url=(t==0)?'http://msg.ua.56.com/api/maybelike.php?&num=34786455&callback=_h.show_likevideo':'http://msg.ua.56.com/api/maybelike.php?&more=1&callback=_h.show_likevideo';jLoader(url,'','','utf8');}else{if($_("may_like_box").className=='sbox may_like box_close'){$_("may_like_box").className='sbox may_like box_open';}else{$_("may_like_box").className='sbox may_like box_close';}}},show_video:function(vars,title,view,play){var splayer='<object width="298" height="224" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000">';splayer+='<param name="movie" value="http://www.56.com/flashApp/v_player_site_index.10.07.05.c.swf">';splayer+='<param value="opaque" name="wmode">';splayer+='<param name="allowScriptAccess" value="always" />';splayer+='<param name="FlashVars" value="'+vars+'">';splayer+='<embed width="298" height="224" src="http://www.56.com/flashApp/v_player_site_index.10.07.05.c.swf" FlashVars="'+vars+'" AllowFullScreen="true" allowScriptAccess="always" wmode="opaque" type="application/x-shockwave-flash" >';splayer+='</embed>';splayer+='</object>';$_("index_video").innerHTML=splayer;$_("index_vt").innerHTML=title;$_("index_cms").innerHTML=view;$_('index_ply').innerHTML=play;},isi:0,view_video:function(i){var str='videodata='+'_^_'+videodata[i].img+'_^_'+videodata[i].flvid+'&vid='+videodata[i].flvid;this.show_video(str,videotitle[i].title,'<s title="参与评论"></s>'+videoview[i].view,'<s title="播放"></s>'+videoview[i].play);if(i!=this.isi){$_("pn_"+this.isi).className='';}
$_("pn_"+i).className='active';this.isi=i;},showPlayRecord:function(){var showRecord=false;var recordHtml='';var rNum=Math.round(Math.random()*10);if(usr.gIsLogin()||_.getCookie('play_rec_conf')||rNum==1){showRecord=true;play_record.init();recordHtml=play_record.sHtml();}
if(showRecord){recordHtml='<div class="sbox record_data box_close" id="record">'+recordHtml+'</div>';document.getElementById('none_recoid').innerHTML=recordHtml;}else{document.getElementById('none_recoid').style.display='none';}},loadweather:function(){var url_3='http://s2.56img.com/script/page/common/v3/homepage_ww_utf8_d_v.2.js';jLoader(url_3,"","",'utf8');},checkaccept:function(){var url='http://w.56.com/API/getaccept.php?callback=_h.showwapban';jLoader(url,"","",'utf8');},showwapban:function(type){switch(type){case'wap':document.getElementById('wapbanner').style.display='';break;case'web':default:break;}},loopsearchkey:function(){var n=Math.floor(Math.random()*10+1);if(searchkeys[n]!=undefined){var title=decodeURIComponent(searchkeys[n]['title']);$('#Search_input').val(title);$('#Search_input_foot').val(title);var search=$_('Search_input');if(search.addEventListener){search.addEventListener('onclick',function(){(new RegExp(title,'ig').exec($_('Search_input').value))?$_('Search_input').value='':'';},false);$_('Search_input_foot').addEventListener('onclick',function(){(new RegExp(title,'ig').exec($_('Search_input_foot').value))?$_('Search_input_foot').value='':'';},false);}else if(search.attachEvent){search.attachEvent('onclick',function(){(new RegExp(title,'ig').exec($_('Search_input').value))?$_('Search_input').value='':'';},false);$_('Search_input_foot').attachEvent('onclick',function(){(new RegExp(title,'ig').exec($_('Search_input_foot').value))?$_('Search_input_foot').value='':'';},false);}}},set_logo_extra:function(){var html='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="90" height="35" id="tileimage" align="middle">';html+='<param name="allowScriptAccess" value="sameDomain" />';html+='<param name="menu" value="false" />';html+='<param name="quality" value="high" />';html+='<param name="movie" value="http://s1.56img.com/style/index/v2/img/qinlan_90x35_2.swf?v=20110530" />';if(!$.browser.msie){html+='<embed src="http://s1.56img.com/style/index/v2/img/qinlan_90x35_2.swf?v=20110530" menu="false" quality="high" width="90" height="35" name="tileimage" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />';}
html+='</object>';$('#logo_extra').length>0?$('#logo_extra').html(html):'';},loadloginjs:function(id){_h.indexLogin(id);if(usr.gIsLogin()){}},zhapiannotice:function(){if(_.getCookie('op_popup_notice')==''){$('#op_popup').show();}},hidezhapian:function(){$('#op_popup').hide();G.setcookie('op_popup_notice','c',9999999);},ready:function(id2,id3){try{this.loadloginjs(id3);this.loopsearchkey();this.getViewCookie();if(typeof PlaylistBar!="undefined"){PlaylistBar.addListBtn();}
setTimeout(_h.loadweather,500);this.attevent();}catch(e){}},readyLogin:function(id2,id3){this.loadloginjs(id3);getViewCookie("now");},getViewCookie:function()
{getViewCookie();},attevent:function(){var search=$_('Search_input');$('#Search_input').attr('autocomplete','off');var btn=$_('Search_btn');btn.onclick='';var delaytime=100;if(search.addEventListener){try{$_('header_serach').addEventListener('onsubmit',function(){setStat('i_search_c');},false);search.addEventListener('input',function(){ajaxsearch();},false);search.addEventListener('blur',function(){resetSearchInVal();hiddensearch();},false);search.addEventListener('focus',function(){create_prompt_list();ajaxsearch();},false);search.addEventListener('keydown',function(event){var e=event;searchkeydown(e);},false);}catch(e){}}else if(search.attachEvent){$_('header_serach').attachEvent('onsubmit',function(){setStat('i_search_c');},false);search.attachEvent('onpropertychange',function(){ajaxsearch();});search.attachEvent('onblur',function(){resetSearchInVal();hiddensearch();});search.attachEvent('onfocus',function(){create_prompt_list();ajaxsearch();},false);search.attachEvent('onkeydown',function(event){var e=event;searchkeydown(e);},false);}}};function fCheck(){var warning=$_('login_tips');var o=$_('loginForm');if(o.e.value==''){warning.innerHTML='<b></b>请输入用户帐号！';o.e.focus();return false;}else if(o.p.value==''){warning.innerHTML='<b></b>请输入用户密码！';o.p.focus();return false;}else if(gel('serialStyle').style.display=="block"&&o.icode.value==''){warning.innerHTML='<b></b>请输入验证码！';o.icode.focus();return false;}
warning.innerHTML='';warning=null;setStat('i_nav_login');o.submit();return true;};function searchFoot(searchform){searchform=searchform||'search';document.charset='utf-8';if(document.forms[searchform].action.indexOf('tieba.56.com')>-1){document.getElementById('kw').value=document.getElementById('Search_input').value;document.getElementById('Search_footinput').value='';}
setStat('i_search_c');document.forms[searchform].submit();return true;}
function flashchangetitle(id){id=id-1;document.getElementById("videoshow_title").innerHTML=videotitle[id]['title'];document.getElementById("videoshow_info").innerHTML=videoinfo[id]['info'];}
function clickthis(m,l,hm,hl){document.getElementById(m).className='active';document.getElementById(l).style.display='block';document.getElementById(hm).className=' ';document.getElementById(hl).style.display='none';}
function mouse_over(){var i,c,numargs=arguments.length;var topshowprefix=arguments[0];var t_length=topshowprefix.length;var is_active=topshowprefix.substr(t_length-1,1);var tab_name=topshowprefix.substr(0,t_length-1);var listshowprefix=arguments[1];var b_length=listshowprefix.length;var con_name=listshowprefix.substr(0,b_length-1);var shownum=arguments[2];var totalnum=arguments[3];if(numargs<5){cname="active";}else{cname=arguments[4];}
for(var i=1;i<=totalnum;i++){if(is_active==i){document.getElementById(tab_name+i).className=cname;document.getElementById(con_name+i).style.display='block';}else{document.getElementById(tab_name+i).className='';document.getElementById(con_name+i).style.display='none';}}
return 0;}
function c_over(topshowprefix,listshowprefix,shownum,totalnum){mouse_over(topshowprefix,listshowprefix,shownum,totalnum,'current');}
function login(){var username=$_('username');var password=$_('password');if(username&&password){username.style.borderBottom="#ffaa00 1px solid";username.style.borderTop="#ffaa00 1px solid";username.style.borderRight="#ffaa00 1px solid";username.style.borderLeft="#ffaa00 1px solid";username.focus();username=null;password.style.borderBottom="#ffaa00 1px solid";password.style.borderTop="#ffaa00 1px solid";password.style.borderRight="#ffaa00 1px solid";password.style.borderLeft="#ffaa00 1px solid";password=null;}}
function login_box_success(){window.location.href=window.location.href.replace(/#/g,'');}
function login_box_error(){var warning=$_('login_tips');var o=$_('urslogin');warning.innerHTML='<b></b>输入的用户名或密码不对哦！';o.username.focus();}
function stop_scroll(){scroll_status=0;}
function run_scrioll(){scroll_status=1;}
function scroller(id){if(scroll_status==0){setTimeout(function(){scroller('scroller_ul');},4000);return;}
$('ul#scroller_ul li:first-child').animate({"margin-top":-76},"normal","linear",function(){var scrollhtml=$('ul#scroller_ul li:first-child').html();$('ul#scroller_ul li:first-child').remove();$('ul#scroller_ul').append('<li onmouseover="scroll_status = 0;" onmouseout="scroll_status = 1;">'+scrollhtml+'</li>');});setTimeout(function(){scroller('scroller_ul');},3000);}(function($){$.fn.scroll=function(options){var opts=$.extend({},$.fn.scroll.deflunt,options);var obj=$(this);this.find("li:first").animate({"margin-top":-opts.scrollH},opts.speed,function(obj){});};$.fn.scroll.deflunt={status:'scroll_status',scrollH:54,speed:'normal',timer:3000};})(jQuery)
function popupsl(){if($.browser.msie&&($.browser.version=="6.0")){var scrollTop=document.documentElement.scrollTop||document.body.scrollTop;var screenHeight=document.documentElement.clientHeight;var popupd=$('#op_popup');var top=scrollTop+screenHeight-popupd.height()-23;popupd.css('top',top+'px');popupd.css('position','absolute');}}
var ztscroll=0;window.onscroll=function(){popupsl();if(ztscroll!=0||(document.documentElement.scrollTop+document.body.scrollTop)<500)return;scroller('scroller_ul');ztscroll=1;}
function changePic(t){if(t==null){t='56_reg';setTimeout(function(){gel('serialImg_login').src='http://icode.renren.com/getcode.do?t='+t+'&rnd='+Math.random();},200);}else{setTimeout(function(){gel('serialImg_login').src='http://icode.renren.com/getcode.do?t='+t+'&rnd='+Math.random();},200);}}
function login_box_error_v3(sCode){var iCode=parseInt(sCode,10);var sMsg="";switch(iCode){case 1:sMsg="您输入的字符不合法";break;case Math.pow(2,1):sMsg="您当前登录的IP已被封禁";break;case Math.pow(2,2):sMsg="帐号或密码错误";gel('loginForm').p.value="";break;case Math.pow(2,3):sMsg="非post访问提交页面";break;case Math.pow(2,4):sMsg="您的账号已停止使用，如有疑问请联系客服";break;case Math.pow(2,5):sMsg="您的帐号未激活";break;case Math.pow(2,6):sMsg="您的帐号由于以下某种原因需要解锁才能登录\n1、删除过帐号\n2、长时间没有登录网站\n3、安全原因";break;case Math.pow(2,7):sMsg="您的用户名和密码不匹配";break;case Math.pow(2,8):sMsg="您的帐号存在安全问题";break;case Math.pow(2,9):sMsg="请输入正确的验证码";break;case Math.pow(2,10):sMsg="您的帐号由于以下某种原因需要解锁才能登录\n1、删除过帐号\n2、长时间没有登录网站\n3、安全原因";break;case Math.pow(2,11):sMsg="您的帐号由于以下某种原因需要解锁才能登录\n1、删除过帐号\n2、长时间没有登录网站\n3、安全原因";break;case Math.pow(2,12):sMsg="默认错误";break;default:sMsg="未知错误";break;}
if(gel('serialStyle').style.display=="block"){gel('loginForm').icode.value="";changePic('56_login');}else{checkUserSafeStatus();}
$_('login_tips').innerHTML="<b></b>"+sMsg;}
function checkUserSafeStatus(){var acc=gel('loginForm').e.value;if(acc&&gel('serialStyle').style.display=="none"){var sUrl="http://user.56.com/index.php?action=Login&do=checkUserSafeStatus&callback=checkUserSafeStatusResult&rand="+Math.random()+"&account="+acc;jLoader(sUrl);}}
function checkUserSafeStatusResult(isSafe){if(isSafe){gel('serialStyle').style.display="none";}else{gel('serialStyle').style.display="block";}}
function gel(a){return document.getElementById?document.getElementById(a):null;}
function show_s_rr_login_auto(uname){var rrLoginTmp='<div class="content">';rrLoginTmp+='<div class="guide_block">';rrLoginTmp+='<div class="msg">';rrLoginTmp+='<p>56网与人人网已帐号合并，可用人人网帐号登录</p>';rrLoginTmp+='</div>';rrLoginTmp+='<p class="check_results">';rrLoginTmp+='<span class="renren_nickname">';if(uname&&uname.length>1){rrLoginTmp+='已检测到您的人人昵称：';rrLoginTmp+='<a href="javascript:void(0)">'+decodeURIComponent(uname)+'</a>';}else{rrLoginTmp+='已检测到您已登录人人网';}
rrLoginTmp+='</span>';rrLoginTmp+='<a class="btn_quick_login" title="快速登录56" href="javascript:submitRenren()">快速登录56</a>';rrLoginTmp+='</p>';rrLoginTmp+='<a class="exit_account" href="javascript:exit_auto_login()">您可以选择退出，使用其他帐号登录</a>';rrLoginTmp+='</div>';rrLoginTmp+='</div>';document.getElementById('login').innerHTML=rrLoginTmp;}
function initLoginBox(){_h.loadloginjs('login');}
function saveViewRecord(){if(!usr.user_id()){show_index_login();}else if(_.e("save_view_cookie")){_.e("save_view_cookie").innerHTML='<a title="更多" href="http://w.56.com/my/index.php?action=Video&do=viewList">更多</a>&nbsp;|&nbsp;<a title="清空记录" href="javascript:void(0)" onclick="clearViewRecord();">清空记录</a>';}}
jQuery_cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{expires:1,path:"\/"};var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toGMTString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()
+(options.expires*60*60*1000));}else{date=options.expires;}
expires='; expires='+date.toGMTString();}
var path=options.path?'; path='+options.path:'';var domain=options.domain?'; domain='+options.domain:'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue='';if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=_.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){try{cookieValue=decodeURIComponent(cookie.substring(name.length+1));}catch(e){cookieValue=unescape(cookie.substring(name.length+1));}
break;}}}
return cookieValue;}};