
var PlaylistBar=(function($){var quicklist=_.getCookie("quicklist"),quicklistData=[],spread=false,spreadBarTimerId=false,isIe6=($.browser.msie&&$.browser.version=='6.0')?true:false,courMaxLength=0,moveLength=0,popTimeter=null,currIndex=-1;function calQuickLength(str){var length=((str!=="")?str.split(",").length:0);return length;}
function creatMinibar(){var vid=location.href.match(/^http:\/\/www\.56\.com\/u\d{2}\/quicklist\.phtml\?id=(\w+)/),isPlay=false,html,tmpQuicklist;html='<div id="playlist_bar" class="playlist_bar">';html+='<div class="hd"><ul class="btns">';if(quicklist&&calQuickLength(quicklist)>0){html+='<li class="play_btn"><a href="#" title="播放" hidefocus="true">播放</a></li><li class="play_next_btn" id="play_next"><a href="#" title="下一个" hidefocus="true" >下一个</a></li>';}else{html+='<li class="play_btn play_dis_btn"><a href="#" title="播放" hidefocus="true">播放</a></li><li class="play_next_btn play_next_dis_btn" id="play_next"><a href="#" title="下一个"  hidefocus="true">下一个</a></li>';}
html+='<li class="toggle_btn"><a href="#" hidefocus="true" ></a></li></ul>';html+='<em class="bar_tit" >点播单</em><em class="bar_tit2" >我的点播单</em></div>';html+='<div class="bd"></div></div>';$("body").append(html);if(vid!==null){vid=vid[1];tmpQuicklist=quicklist.split(",");currIndex=tmpQuicklist.indexOf(vid);if(currIndex!=-1&&quicklistData[currIndex+1]){if(oFlv){oFlv.dianboNextUrl=quicklistData[currIndex+1].url;}}
if(currIndex!==-1&&(_.getCookie("toggle_playlistbar")=="toggle"||_.getCookie("toggle_playlistbar")=="")){spread=true;$("#playlist_bar").addClass("playlist_bar_op");insertHtml('afterend',document.getElementById("play_next"),'<li class="clear_btn" id="play_clear"><a href="#" title="清空" hidefocus="true">清空</a></li>');creatList();initCurPos();if(_.getCookie("toggle_playlistbar")==""){_.setCookie("toggle_playlistbar","toggle",24,".56.com");spreadBarTimerId=setTimeout(function(){spreadBar();},"4000");}}}}
function fixed(elem){var fixTop,fixLeft,elemWidth;try{if(spread){fixTop=$(window).height()+$(document).scrollTop()-184;fixLeft=$(document).scrollLeft();elemWidth=$(window).width();elem.css({top:fixTop,left:fixLeft,width:elemWidth}).show();elem.css({top:fixTop,left:fixLeft}).show();}else{fixTop=$(window).height()+$(document).scrollTop()-34;elem.css({top:fixTop,left:"",width:"200px"}).show();}}catch(e){}}
function bindMiniBarEven(){try{var elem=$("#playlist_bar"),ieScrollTimer=null;if(isIe6){$(window).resize(function(){clearTimeout(ieScrollTimer);elem.hide();ieScrollTimer=setTimeout(function(){fixed(elem);},500);});$(window).bind("scroll",function(){clearTimeout(ieScrollTimer);elem.hide();ieScrollTimer=setTimeout(function(){fixed(elem);},500);});}
$(window).resize(function(){initCaro();});elem.delegate(".toggle_btn","click",function(event){setStat("vod_0_07111825");if(spreadBarTimerId!==false){try{clearTimeout(spreadBarTimerId);}catch(e){}
spreadBarTimerId=true;}
spreadBar(this);return false;});elem.delegate(".bar_tit","click",function(event){setStat("vod_0_07111825");spreadBar(this);if(spreadBarTimerId!==false){try{clearTimeout(spreadBarTimerId);}catch(e){}
spreadBarTimerId=true;}
return false;});elem.delegate(".del_btn","click",function(event){setStat("vod_0_07111813");delVideo(this);return false;});elem.delegate(".clear_btn","click",function(event){if(quicklist!=""){setStat("vod_0_07111753");popTips("dellist");}});elem.delegate(".play_next_btn","click",function(event){setStat("vod_0_07111743");if(oFlv.dianboNextUrl&&oFlv.dianboNextUrl!==undefined){window.location=oFlv.dianboNextUrl;}else if(quicklistData&&quicklistData.length>0){oFlv.dianboNextUrl=quicklistData[0].url;window.location=oFlv.dianboNextUrl;}
return false;});elem.delegate(".play_btn","click",function(event){setStat("vod_0_12163405");playVideo(quicklistData[0]);return false;});elem.delegate(".list_cont","mouseover",function(){if(spreadBarTimerId!==false){try{clearTimeout(spreadBarTimerId);}catch(e){}
spreadBarTimerId=false;}});elem.delegate(".list_cont","mouseout",function(){if(spreadBarTimerId===false){spreadBarTimerId=setTimeout(function(){spreadBar();},"4000");}});elem.delegate(".pre a","click",function(event){scrollPre();return false;});elem.delegate(".next a","click",function(event){scrollNext();return false;});}catch(e){}}
function delList(e){var self=$(e),html="",quickAry,btn=null;if(!self.hasClass("clear_dis_btn")){var elem=$(elem),vid=elem.attr("vid");quickAry=quicklist.split(",");for(var i=0;i<quickAry.length;i++){btn=document.getElementById("pid_"+quickAry[i]);btn&&(btn.className="m_v_list_add add_to_list");}
if(usr.user_id()!==""&&quicklist!==""){jLoader('http://www.56.com/w20/dianbo/api/del.php?user_id='+usr.user_id()+'&vid='+quicklist);}
quicklist="";_.setCookie("quicklist",quicklist,8750,".56.com");quicklistData=[];if(spread){html='<div class="msg_cont" ><p>您还未添加视频到点播单，您可以到<a href="//www.56.com">首页</a>或者<a href="//video.56.com/">视频列表</a>寻找你喜欢的。</p></div>';$("#playlist_bar .bd").html(html);}
countNum();}
$('#playlist_bar .pop_msg').fadeOut('200');return false;}
function spreadBar(elem){var bar=$("#playlist_bar");bar.hide();if(spread===true){bar.removeClass("playlist_bar_op");if(document.getElementById("play_clear")){$("#play_clear").remove();}
_.setCookie("toggle_playlistbar","notoggle",24,".56.com");spread=false;}else{creatList();$("#playlist_bar .sup").remove();bar.addClass("playlist_bar_op");_.setCookie("toggle_playlistbar","toggle",24,".56.com");if(document.getElementById("play_next")&&quicklist&&calQuickLength(quicklist)>0){insertHtml('afterend',document.getElementById("play_next"),'<li class="clear_btn" id="play_clear"><a href="#" title="清空" hidefocus="true">清空</a></li>');}else if(document.getElementById("play_next")){insertHtml('afterend',document.getElementById("play_next"),'<li class="clear_btn clear_dis_btn" id="play_clear"><a href="#" title="清空" hidefocus="true">清空</a></li>');}
spread=true;}
countNum();if(isIe6){fixed(bar);}else{bar.show();}}
function insertHtml(where,el,html){where=where.toLowerCase();if(el.insertAdjacentHTML){switch(where){case"beforebegin":el.insertAdjacentHTML('BeforeBegin',html);return el.previousSibling;case"afterbegin":el.insertAdjacentHTML('AfterBegin',html);return el.firstChild;case"beforeend":el.insertAdjacentHTML('BeforeEnd',html);return el.lastChild;case"afterend":el.insertAdjacentHTML('AfterEnd',html);return el.nextSibling;}
throw'Illegal insertion point -> "'+where+'"';}
var range=el.ownerDocument.createRange();var frag;switch(where){case"beforebegin":range.setStartBefore(el);frag=range.createContextualFragment(html);el.parentNode.insertBefore(frag,el);return el.previousSibling;case"afterbegin":if(el.firstChild){range.setStartBefore(el.firstChild);frag=range.createContextualFragment(html);el.insertBefore(frag,el.firstChild);return el.firstChild;}else{el.innerHTML=html;return el.firstChild;}
case"beforeend":if(el.lastChild){range.setStartAfter(el.lastChild);frag=range.createContextualFragment(html);el.appendChild(frag);return el.lastChild;}else{el.innerHTML=html;return el.lastChild;}
case"afterend":range.setStartAfter(el);frag=range.createContextualFragment(html);el.parentNode.insertBefore(frag,el.nextSibling);return el.nextSibling;}
throw'Illegal insertion point -> "'+where+'"';}
function countNum(){var html,num=calQuickLength(quicklist),playlist_bar=$("#playlist_bar"),cIndex;if(spread===false){html='<span class="sup">'+num+'<i></i></span>';playlist_bar.find(".bar_tit>.sup").remove();playlist_bar.find(".bar_tit").append(html);}else{if(currIndex!==-1){cIndex=currIndex+1
html='<span>('+cIndex+'/'+num+')</span>';}else{html='<span>('+num+')</span>';}
playlist_bar.find(".bar_tit2>span").remove();playlist_bar.find(".bar_tit2").append(html);}
if(num===0){playlist_bar.find(".clear_btn").addClass("clear_dis_btn");playlist_bar.find(".play_next_btn").addClass("play_next_dis_btn").hide();playlist_bar.find(".play_btn").addClass("play_dis_btn").show();}else{playlist_bar.find(".clear_btn").removeClass("clear_dis_btn");if(currIndex!==-1){if(currIndex===calQuickLength(quicklist)){playlist_bar.find(".play_next_btn").hide();playlist_bar.find(".play_btn").removeClass("play_dis_btn").show();}else{playlist_bar.find(".play_next_btn").removeClass("play_next_dis_btn").show();playlist_bar.find(".play_btn").hide();;}}else{playlist_bar.find(".play_next_btn").hide();playlist_bar.find(".play_btn").removeClass("play_dis_btn").show();}}}
function creatList(){var html="",playlist_bar_bd=$("#playlist_bar .bd");playlist_bar_bd.html(""),target="_self";if(quicklistData.length!==0){html+='<div class="list_cont"><span class="pre"><a href="#" class="disable"></a></span><span class="next" ><a href="#" class="disable"></a></span><div class="cour"><ul id="cour_list">'
for(var i=0;i<quicklistData.length;i++){if(currIndex===i){html+='<li class=\'current\' onclick="setStat(\'vod_0_07111834\')" onmouseover="this.className=\'current hover\'" onmouseout="this.className=\'current\'">';}else{html+='<li onclick="setStat(\'vod_0_07111834\')" onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'">';}
if(currIndex!==-1){target="_self";}else{target="_blank";}
html+='<a target="'+target+'" href="'+quicklistData[i].url+'" class="img"><img src="'+quicklistData[i].img+'" alt="'+quicklistData[i].title+'"></a>'
html+='<a target="'+target+'" href="'+quicklistData[i].url+'" class="vtit">'+quicklistData[i].title+'</a>';html+='<span class="del_btn" title="删除" vid="'+quicklistData[i].vid+'"></span>'
html+="</li>";}
html+="</ul></div></div>";playlist_bar_bd.html(html);initCaro();}else{if(_.getCookie("quicklistTuto")==""){_.setCookie("quicklistTuto","true",8750,".56.com");playlist_bar_bd.html('<div class="tech_cont"></div>');}else{html='<div class="msg_cont" ><p>您还未添加视频到点播单，您可以到<a href="//www.56.com">首页</a>或者<a href="//video.56.com/">视频列表</a>寻找你喜欢的。</p></div>';playlist_bar_bd.html(html);}}}
function addListBtn(){var images=document.images,i,link,url,vid,quickListLength=calQuickLength(quicklist),j=quicklist.split(",");for(i=0;i<images.length;i++){link=$(images[i]).parent();url=link.attr("href");if(url!==undefined){vid=url.match(/^http:\/\/www\.56\.com\/u\d{2}\/v_(\w+)\.html/);if(vid){vid=vid[1];link.after("<a href='javascript:void(0)' title='加入点播单' id='pid_"+vid+"' class='m_v_list_add add_to_list' _img='"+images[i].src+"' _title='"+link.attr("title")+"' onclick='PlaylistBar.add(this);'></a>");}else{vid=url.match(/^http:\/\/www\.56\.com\/w\d{2}\/play_album-aid-(\d+)_vid-(\w+)\.html/);if(vid){vid=vid[2];link.after("<a href='javascript:void(0)' title='加入点播单' id='pid_"+vid+"' class='m_v_list_add add_to_list' _img='"+images[i].src+"' _title='"+link.attr("title")+"' onclick='PlaylistBar.add(this);'></a>");}}}}
for(i=0;i<quickListLength;i++){$("#pid_"+j[i]).removeClass("add_to_list").addClass("added_to_list");$("#pid_"+j[i]).attr("title","打开点播单");}}
function scrollNext(){var courList=$("#cour_list"),left=-moveLength*162+parseInt(courList.css("left"));if(courList.attr("scrolling")==true){return false;}
courList.attr("scrolling",true);if(left>courMaxLength){courList.animate({"left":left},200,function(){$(this).attr("scrolling",false);checkCaro();});}else{courList.animate({"left":courMaxLength},200,function(){$(this).attr("scrolling",false);checkCaro();});}}
function scrollPre(){var courList=$("#cour_list"),left=moveLength*162+parseInt(courList.css("left"));if(courList.attr("scrolling")==true){return false;}
courList.attr("scrolling",true);if(left<0){courList.animate({"left":left},200,function(){$(this).attr("scrolling",false);checkCaro();});}else{courList.animate({"left":0},200,function(){$(this).attr("scrolling",false);checkCaro();});}}
function initCaro(){try{var courList=$("#cour_list");moveLength=Math.floor(($(window).width()-52)/162);if((courList.children().length-moveLength)>0){courMaxLength=-(courList.children().length-moveLength)*162;}else{courMaxLength=0;}
checkCaro();}catch(e){}}
function initCurPos(){try{var courList=$("#cour_list"),left=-162*currIndex;if(left<=courMaxLength){left=courMaxLength;}
courList.css("left",left);checkCaro();}catch(e){}}
function checkCaro(){var playlist_bar=$("#playlist_bar"),left;try{left=parseInt($("#cour_list").css("left"));if(left===0){playlist_bar.find(".pre>a").addClass("disable");}else{playlist_bar.find(".pre>a").removeClass("disable");}
if(left<=courMaxLength){playlist_bar.find(".next>a").addClass("disable");}else{playlist_bar.find(".next>a").removeClass("disable");}}catch(e){}}
function popTips(n,o){var html="";clearTimeout(popTimeter);switch(n){case"full":html='<div class="pop_msg" ><h4>提示：</h4><div class="msg_info"><p>你好，你已经添加了40个视频到点播单，请登录或者清理一些已观看过的</p><a href="#" onclick="PlaylistBar.delList(this);return false;">清空点播单</a></div></div>';break;case"hover":if(quicklist!==""&&quicklistData.length!==0){html='<div class="pop_msg pop_msg_hover" ><h4>我的点播单（'+calQuickLength(quicklist)+'）</h4><div class="vinfo"><a href="'+quicklistData[0].url+'" class="img"><img src="'+quicklistData[0].img+'" ></a><p><a href="'+quicklistData[0].url+'">'+quicklistData[0].title+'</a></p></div></div>';}
break;case"add":html='<div class="pop_msg" onclick="setStat(\'vod_0_07111733\')"><h4>已添加到点播单</h4><div class="vinfo"><a href="'+o.url+'" class="img"><img src="'+o.img+'" ></a><p><a href="'+o.url+'">'+o.title+'</a></p></div></div>';break;case"next":html='<div class="pop_msg" ><h4>下一个视频（'+calQuickLength(quicklist)+'）</h4><div class="vinfo"><a href="'+o.url+'" class="img"><img src="'+o.img+'" ></a><p><a href="'+o.url+'">'+o.title+'</a></p></div></div>';break;case"merger":html='<div class="pop_msg" ><h4>提示：</h4><div class="msg_info"><p>你好，登录前点播单中有'+calQuickLength(quicklist)+'个视频，需要合并吗？</p><p class="btns"><a href="#" onclick="mergerQuicklistData();return false;" class="l_btn">确认</a><a href="#" onclick="$(\'#playlist_bar .pop_msg\').fadeOut(\'200\');return false;" class="l_btn">取消</a></p></div></div>';break;case"dellist":html='<div class="pop_msg" ><h4>提示：</h4><div class="msg_info"><p>您好，确认要清空点播单吗？</p><p class="btns"><a href="#" onclick="PlaylistBar.delList(this);return false;" class="l_btn">确认</a><a href="#" onclick=\"$(\'#playlist_bar .pop_msg\').fadeOut(\'200\');return false;\" class="l_btn">取消</a></p></div></div>';break;default:html="";}
$("#playlist_bar .pop_msg").remove();$("#playlist_bar").append(html);$("#playlist_bar .pop_msg").fadeIn("200");popTimeter=setTimeout(function(){if($("#playlist_bar .pop_msg")!==undefined){$("#playlist_bar .pop_msg").fadeOut("200",function(){$(this).remove();});}},30000);}
function loadCss(fn){var eyecm=document.createElement('link');eyecm.href='http://s1.56img.com/script/ui/playlistbar/v1/playlistbar_v.1.css';eyecm.rel='stylesheet';document.getElementsByTagName('head')[0].appendChild(eyecm);fn();}
function playVideo(o){if(currIndex===-1&&o&&o.url!=""){window.open(o.url);}else if(o&&o.url!=""){window.location=o.url;}}
function addVideo(elem){var elem=$(elem),videoObj={},html="",target="_self";videoObj.vid=elem.attr("id").split("_")[1];videoObj.url="http://www.56.com/u20/quicklist.phtml?id="+videoObj.vid;videoObj.title=elem.attr("_title");videoObj.img=elem.attr("_img");elem.attr("title","打开点播单");if(elem.hasClass("added_to_list")){setStat("vod_0_07111723");playVideo(videoObj);}else{setStat("vod_0_07111712");if(calQuickLength(quicklist)>=40){popTips("full");}else{elem.removeClass("add_to_list").addClass("added_to_list");if(quicklist.indexOf(videoObj.vid)==-1){if(currIndex!==-1){target="_self";}else{target="_blank";}
if(quicklist===""){quicklist=videoObj.vid;if(spread){html='<div class="list_cont"><span class="pre"><a href="#" class="disable"></a></span><span class="next"><a href="#" class="disable"></a></span><div class="cour"><ul id="cour_list">';html+='<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'" ><a target="'+target+'" href="'+videoObj.url+'" class="img"><img src="'+videoObj.img+'" alt="'+videoObj.title+'"></a>'
html+='<a target="'+target+'" href="'+videoObj.url+'" class="vtit">'+videoObj.title+'</a>';html+='<span class="del_btn" title="删除" vid="'+videoObj.vid+'"></span></li>';html+='</ul></div></div>';$("#playlist_bar .bd").html(html);}}else{quicklist+=(","+videoObj.vid);if(spread){html+='<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'"><a target="'+target+'" href="'+videoObj.url+'" class="img"><img src="'+videoObj.img+'" alt="'+videoObj.title+'"></a>'
html+='<a target="'+target+'" href="'+videoObj.url+'" class="vtit">'+videoObj.title+'</a>';html+='<span class="del_btn" title="删除" vid="'+videoObj.vid+'"></span></li>';$("#cour_list").append(html);}}
quicklistData.push(videoObj);if(typeof oFlv!="undefined"&&videoObj.url&&oFlv.dianboNextUrl===undefined){oFlv.dianboNextUrl=videoObj.url;}
_.setCookie("quicklist",quicklist,8750,".56.com");if(usr.user_id()!==""){jLoader('http://www.56.com/w20/dianbo/api/add.php?user_id='+usr.user_id()+'&vid='+videoObj.vid);}
popTips("add",videoObj);initCaro();countNum();}}}}
function delVideo(elem){var elem=$(elem),vid=elem.attr("vid");if(quicklist.indexOf(vid)!==-1){setStat("vod_0_07111813");quicklist=quicklist.replace(","+vid,"");quicklist=quicklist.replace(vid+",","");quicklist=quicklist.replace(vid,"");_.setCookie("quicklist",quicklist,8750,".56.com");quicklistData=quicklistData.filter(function(elem,index,array){return elem.vid!==vid;});$("#pid_"+vid).removeClass("added_to_list").addClass("add_to_list");if(quicklist===""){creatList();}else{elem.parents("li").remove();}
initCaro();countNum();if(usr.user_id()!==""){jLoader('http://www.56.com/w20/dianbo/api/del.php?user_id='+usr.user_id()+'&vid='+vid);}}}
function addPerListBtn(){if(navigator.userAgent.toLowerCase().indexOf('ipad')==-1&&window.location.href.indexOf('#sm_ipad')==-1){var i,quickListLength=calQuickLength(quicklist),j=quicklist.split(",");for(i=0;i<quickListLength;i++){$("#pid_"+j[i]).removeClass("add_to_list").addClass("added_to_list");$("#pid_"+j[i]).attr("title","打开点播单");}}}
function initDianboList(o){var tmpData="";try{document.charset='utf-8';document.domain="56.com";}catch(e){};var status=o.status;if(status==1){quicklistData=o.data;}
loadCss(function(){$(document).ready(function(){creatMinibar();bindMiniBarEven();countNum();});});}
function merger(o){if(o!=""&&o.status==1){quicklistData=o.data;quicklist=o.quicklist;_.setCookie('quicklist',quicklist,8750,'.56.com');if(spread===true){creatList();}
countNum();addPerListBtn();}}
(function init(){if(navigator.userAgent.toLowerCase().indexOf('ipad')==-1&&window.location.href.indexOf('#sm_ipad')==-1){}})();return{add:function(elem){if(document.getElementById("playlist_bar")){addVideo(elem);}},initDianboList:function(o){initDianboList(o);},mergerPop:function(){if(usr.user_id()!==""&&quicklist==""){loadQuicklistData();}else{popTips("merger");}},addListBtn:addListBtn,checkListBtn:addPerListBtn,merger:function(o){merger(o);},delList:delList}})(jQuery);if(!Array.prototype.filter){Array.prototype.filter=function(fun){var len=this.length;if(typeof fun!="function")
throw new TypeError();var res=new Array();var thisp=arguments[1];for(var i=0;i<len;i++){if(i in this){var val=this[i];if(fun.call(thisp,val,i,this))
res.push(val);}}
return res;};}
if(!Array.prototype.indexOf){Array.prototype.indexOf=function(elt){var len=this.length;var from=Number(arguments[1])||0;from=(from<0)?Math.ceil(from):Math.floor(from);if(from<0)
from+=len;for(;from<len;from++){if(from in this&&this[from]===elt)
return from;}
return-1;};}
function mergerQuicklistData(){$('#playlist_bar .pop_msg').fadeOut('200');if(usr.user_id()!==""){var quicklist=_.getCookie("quicklist");jLoader('http://www.56.com/w20/dianbo/api/get.php?user_id='+usr.user_id()+'&vid='+quicklist+'&action=merge&callback=PlaylistBar.merger');}}
function loadQuicklistData(){var quicklist=_.getCookie("quicklist");if(usr.user_id()!==""&&quicklist==""){jLoader('http://www.56.com/w20/dianbo/api/get.php?user_id='+usr.user_id()+'&vid='+quicklist+'&action=merge&callback=PlaylistBar.merger');}}