
function loaderRenrenIframe(){var tmpStr="";try{document.charset='utf-8';document.domain="56.com";var url="http://www.renren.com/c-signin?d=56.com&u=";tmpStr+='<iframe id="renren_login" width="0" scrolling="0" style="display:block" height="0" frameborder="0" name="renren_login" src="" marginwidth="0" marginheight="0"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>56</title><meta content="application/xhtml+xml; charset=utf-8" http-equiv="content-type"></head><body></body></html></iframe>';tmpStr+='<form name="renren_form" action="http://www.renren.com/c-signin" method="get" target="renren_login" id="renren_form">';tmpStr+='<input type="hidden" name="d" value="56.com">';tmpStr+='<input type="hidden" name="u" value="http://www.56.com/renren_s.html|http://www.56.com/renren_f.html">';tmpStr+='</form>';var b=document.getElementsByTagName("body")[0];if(b){var div=document.createElement('div');div.innerHTML=tmpStr;b.appendChild(div);}else{document.write(tmpStr);}}catch(e){set_renren_auto_cookie();};}
function loaderRenrenLoginIframe(){var tmpStr="";try{document.charset='utf-8';document.domain="56.com";var url="http://www.renren.com/c-signin?d=56.com&u=";tmpStr+='<iframe id="renren_auto_login" width="0" scrolling="0" style="display:block" height="0" frameborder="0" name="renren_auto_login" src="" marginwidth="0" marginheight="0"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>56</title><meta content="application/xhtml+xml; charset=utf-8" http-equiv="content-type"></head><body></body></html></iframe>';tmpStr+='<form name="renren_auto_form" action="http://www.renren.com/c-signin" method="get" target="renren_auto_login" id="renren_auto_form">';tmpStr+='<input type="hidden" name="d" value="56.com">';tmpStr+='<input type="hidden" name="u" id="renren_reg_iframe" value="http://www.56.com/renren_auto_login_s.html|http://www.56.com/renren_f.html">';tmpStr+='</form>';var b=document.getElementsByTagName("body")[0];if(b){var div=document.createElement('div');div.innerHTML=tmpStr;b.appendChild(div);}else{document.write(tmpStr);}}catch(e){};}
function submitRenren(){if(document.getElementById('renren_form')){try{document.getElementById('renren_form').submit();}catch(e){set_renren_auto_cookie();}}}
function exit_auto_login(auto_logout_iframe){try{initLoginBox();if(auto_logout_iframe){document.getElementById(auto_logout_iframe).src="http://urs.56.com/php/logout.php?ourl=http://www.56.com/renren_logout.html";}else{document.getElementById("renren_auto_login").src="http://urs.56.com/php/logout.php?ourl=http://www.56.com/renren_logout.html";}}catch(e){}}
function submitRenren2(){if(document.getElementById('renren_auto_form')){try{document.getElementById('renren_auto_form').submit();}catch(e){set_renren_auto_cookie();}}}
if(typeof(_)=="undefined"||typeof(_.getCookie)!="function"||typeof(_.setCookie)!="function"){var _={getCookie:function(name){return jQuery_cookie(name);},setCookie:function(name,value,hours,domain){var options={};if(hours)
options.expires=hours;if(domain)
options.domain=domain;options.path="\/";jQuery_cookie(name,value,options);},trim:function(text){return(text||"").replace(/^\s+|\s+$/g,"");}};}
if(typeof(jQuery_cookie)!="function"){jQuery_cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{expires:1,path:"\/"};var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toGMTString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()
+(options.expires*60*60*1000));}else{date=options.expires;}
expires='; expires='+date.toGMTString();}
var path=options.path?'; path='+options.path:'';var domain=options.domain?'; domain='+options.domain:'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue='';if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=_.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){try{cookieValue=decodeURIComponent(cookie.substring(name.length+1));}catch(e){cookieValue=unescape(cookie.substring(name.length+1));}
break;}}}
return cookieValue;}};}
if(typeof(renren_show_login)!="function"){renren_show_login=function(){set_renren_auto_cookie();}}
if(typeof(renren_refresh)!="function"){renren_refresh=function(){window.location.reload();return false;}}
function get_renren_auto_cookie(){return _.getCookie('renren_autoload');}
function check_renren_load(){if(!_.getCookie('renren_autoload').length&&!_.getCookie("member_id").length){return false;}else{return true;}}
if(!check_renren_load()){loaderRenrenIframe();}
function set_renren_auto_cookie(){try{_.setCookie('renren_autoload','renren',0.25,'56.com');}catch(e){}}
function auto_login(){if(!check_renren_load()){loaderRenrenLoginIframe();setTimeout("submitRenren2()",2000);}}
if(typeof(auto_renren_login)!="undefined"&&auto_renren_login=="rr_check_login"){auto_login();}