
document.domain="56.com";var dc=document;var scripts=dc.getElementsByTagName("script");var datas=scripts[scripts.length-1].src.split("?");var querystring="";if(datas.length>1){datas.shift();querystring=datas.join("");}
querystring=querystring.split("&");var _get={};if(querystring.length>1){for(var i=0;i<querystring.length;i++){var tmp=querystring[i].split("=");_get[tmp[0]]=tmp[1];}}
var weibo=window.weibo||{};weibo=(function(){var config={"host":"app.56.com"+(_get['port']?":"+_get['port']:""),"path":"/cooperate/index.php","icon":['怒','吐','赞','吃惊','抱抱','泪','太开心','嘻嘻'],"notUsed":false,"setting":{"sina":{"title":"新浪微博","cls":"rp_tsina","windowParam":'location=yes,left=200,top=100,width=620,height=400,resizable=yes',"disp":true},"qzone":{"title":"QQ空间","cls":"rp_qq","windowParam":'location=yes,left=200,top=100,width=502,height=400,resizable=yes',"disp":true},"qq":{"title":"腾讯微博","cls":"rp_tqq","windowParam":'location=yes,left=200,top=100,width=820,height=730,resizable=yes',"disp":true},"baidu":{"title":"百度","cls":"rp_baidu","windowParam":'location=yes,left=200,top=100,width=560,height=350,resizable=yes',"disp":true},"m139":{"title":"139邮箱","cls":"rp_139","windowParam":'location=yes,left=200,top=100,width=950,height=460,resizable=yes',"disp":true}}};return{"version":"1.0","comment_text":"","pic_url":"","site_url":"","sinaOpen":1,"icon":['`a_angry`','`a_35`','`a_cool`','`a_53`','`a_lol`','`a_96`','`a_36`','`a_heart`'],"from":"comment","tag":'',"sync":function(from,vid){var that=this;var from=from||'up';var vid=vid||'';var txt=txt||'';var pic_url='';var site_url='';try{var wbApi=function(type){var type=type;var param=[];var text=that.comment_text;if(6!=type){vid=vid?vid:oFlv.o.EnId;}
param.push("action=Weibo");param.push("do=Rec");param.push("from="+from);param.push("type="+type);param.push("vid="+vid);if(text){text=text.replace(/\[quote\d*\].*\[\/quote\d*\]/,"");var pt='';for(var i=0;i<that.icon.length;i++){pt=new RegExp(that.icon[i],'g');text=text.replace(/\[`[a-zA-Z0-9_]*`\]/g,'');}
text=encodeURIComponent(text);param.push("text="+text);}else{var title=document.title;title=encodeURIComponent(title.substr(0,title.indexOf('-')));if(title)
param.push("title="+title);}
if(pic_url){param.push("purl="+encodeURIComponent(pic_url));}
if(site_url){param.push("surl="+encodeURIComponent(site_url));}
var src=that.getPath()+'?'+param.join('&');that.send(src);};if(usr.user_id()&&that.getCookie()){var ck=that.getCookie();for(var i in ck){if(i!='bind'){setStat('wbs_'+i);}}
if(from!='fav'&&ck['sina']=='true'){weibo.checkSinaToken(from);}
if(from=="up"){setTimeout(wbApi(3),500);}else if(from=="down"){setTimeout(wbApi(4),500);}else if(from=="fav"){setTimeout(wbApi(5),500);}else if(from=="comment"){wbApi(2);}else if(from=="upload"){setTimeout(wbApi(1),500);}else if(from=="hd"){pic_url=that.pic_url;site_url=that.site_url;wbApi(6);}else if(from=="record"){pic_url=that.pic_url;site_url=that.site_url;wbApi(8);}}
that.reset();}catch(e){if(usr.user_id()=='onesec'){alert('微博接口异常');}}},"send":function(src){if(document.getElementById('sync_weibo')){document.getElementsByTagName('body')[0].removeChild(document.getElementById('sync_weibo'));}
var iframe=document.createElement("iframe");iframe.setAttribute("width",0);iframe.setAttribute("height",0);iframe.setAttribute("name","sync_weibo");iframe.setAttribute("src",src);document.getElementsByTagName('body')[0].appendChild(iframe);return true;},"reset":function(){var that=this;that.comment_text="";that.pic_url="";that.site_url="";that.from="comment";},"getPath":function(){var that=this;return"http://"+config.host+config.path;},"getCookie":function(){var that=this;var _cookie=_.getCookie("weibo");var check=false;if(_cookie){_cookie=eval('('+_cookie+')');if(_cookie['bind']==1){return _cookie;}else{return'';}}else{var urls=that.getUrl('GetStatus','','');jLoader(urls,true);var _ck=_.getCookie("weibo");if(_ck){_ck=eval('('+_ck+')');if(_ck['bind']==1){return _ck;}else{return'';}}else{return'';}}},'setCookie':function(val){if(val){_.setCookie('weibo',val,720,'56.com');}},'checkSinaToken':function(from){var that=this;var _stl=_.getCookie("weibo_stl");var _fucksina=_.getCookie("weibo_sf");if(!_stl){var urls=that.getUrl('GetSinaTokenLimit','','');jLoader(urls,true);var _stl=_.getCookie("weibo_stl");}
if(_stl=='pass'&&!_fucksina){that.tipsSinaToken(from);}},'openSinaLogin':function(winid){if(weibo.sinaOpen>0){_.setCookie("weibo_stl",null,-1,'56.com');if($('#'+winid)){$('#'+winid).remove();}
weibo.connect('sina','loginbox');}},"tipsSinaToken":function(from){var stip='您的新浪微博绑定需要更新，5秒后为您跳转更新';if(from=='comment'){var sbutton='<a class="update_now_cmt_btn" href="javascript:;" onclick="weibo.openSinaLogin()">立即更新</a>';var s=[360,160];var arr=["update_bind_cmt","comment_sina","update_bind_cmt_content","target_comm_postmainid","update_bind_cmt_close"];}else{var sbutton='<a class="update_now_btn" href="javascript:;" onclick="weibo.openSinaLogin()">立即更新</a>';var s=[0,45];var arr=["update_bind","dingcai_sina","update_bind_content","play_action","update_bind_close"];}
var _that=this;setTimeout(function(){_that.openSinaLogin(arr[1]);},5000);this.tipsInit(s,stip,sbutton,arr);},"closeTips":function(id){weibo.sinaOpen=0;_.setCookie('weibo_sf',1,24,'56.com');$('#'+id).remove();},"tipsInit":function(s,stip,sbutton,arr){var str='';str+='<div class="'+arr[0]+'" id="'+arr[1]+'" style="left:'+s[0]+'px;top:'+s[1]+'px;z-index:999;display:block">';str+='<s class="q_tips_arrow"></s><a href="javascript:;" class="'+arr[4]+'" onclick="weibo.closeTips(\''+arr[1]+'\')">X</a>';str+='<div class="'+arr[2]+'">';str+='<p>'+stip+'</p>';str+='</div>';str+=sbutton;str+='</div>';if($('#'+arr[1])){$('#'+arr[1]).remove();}
$("#"+arr[3]).append(str);},'connect':function(tag,from){var that=this;var url=that.getUrl('connect',from,tag);if('baidu'==tag){url+='&fr=bd';}
that.tag=tag;that.openWin(url,tag);return true;},'openWin':function(url,type){var that=this;var param,title;var conf=config.setting[type];title=conf.title;param=conf.windowParam;that.openW=window.open(url,title,param);},'close':function(){var that=this;if(that.openW!=null)
that.openW.close();},'setNotice':function(obj){var that=this;var src=that.getUrl('notify');if(obj.checked==true){src+='&check=1';}else{src+='&check=0';}
jLoader(src,true);},'getUrl':function(op,from,tag){var that=this;var from=from||'';if(tag=='m139'){tag='139';}
var tag=tag||'';var param=[];param.push("action=Weibo");param.push("do="+op);param.push("from="+from);param.push("tag="+tag);return that.getPath()+'?'+param.join('&');},'getIcon':function(from){var tpl='<a onclick="javascript:weibo.connect(\'<{tag}>\',\'<{from}>\');" href="javascript:void(0);" class="<{cls}>" title="用<{tag_name}>帐号登录"><{tag_name}></a>';var h=[];if('home'==from||'tiebabox'==from||'photobox'==from||'dvbox'==from){h.push('<label>其它帐号登录：</label>');}
if('regbox'==from){h.push('<h2>您也可以使用以下帐号登录：</h2>');}
var tpls='';for(var t in config.setting){if(config.setting[t].disp==true){if(config.notUsed){tpls='<a onclick="javascript:alert(\'服务器维护中,此功能暂不开放\');" href="javascript:void(0);" class="<{cls}>" title="用<{tag_name}>帐号登录"><{tag_name}></a>';}else{if('renren'==t){tpls='<a href="http://user.56.com/login/?note=renren" class="<{cls}>" title="用<{tag_name}>帐号登录"><{tag_name}></a>';}else{tpls=tpl;}}
tpls=tpls.replace(/<\{tag\}>/g,t);tpls=tpls.replace(/<\{from\}>/g,from);tpls=tpls.replace(/<\{tag_name\}>/g,config.setting[t].title);tpls=tpls.replace(/<\{cls\}>/g,config.setting[t].cls);h.push(tpls);}}
return h.join('');},'getRegIconList':function(){var h=[];var from='regbox';h.push('<dl class="lgn_loginType_list">');h.push('<dt>其他合作帐号</dt>');var tpls='';for(var t in config.setting){if(config.setting[t].disp==true){if(config.notUsed){tpls='<dd><a onclick="javascript:alert(\'服务器维护中,此功能暂不开放\');" href="javascript:void(0);" title="用<{tag_name}>帐号登录" class="gray"><i class="<{cls}>"></i><{tag_name}></a></dd>';}else if(t!='renren'){tpls='<dd><a onclick="javascript:weibo.connect(\'<{tag}>\',\'<{from}>\');" href="javascript:void(0);" title="用<{tag_name}>帐号登录" class="gray"><i class="<{cls}>"></i><{tag_name}></a></dd>';}
tpls=tpls.replace(/<\{tag\}>/g,t);tpls=tpls.replace(/<\{from\}>/g,from);tpls=tpls.replace(/<\{tag_name\}>/g,config.setting[t].title);tpls=tpls.replace(/<\{cls\}>/g,config.setting[t].cls);h.push(tpls);}}
h.push('</dl>');return h.join('');},'getXiuIconList':function(fr){var h=[];if(!fr||fr==''){fr='xiu';}
var from=fr;h.push('<dl class="lgn_loginType_list">');h.push('<dt>其他合作帐号</dt>');var tpls='';for(var t in config.setting){if(config.setting[t].disp==true){if(config.notUsed){tpls='<dd><a onclick="javascript:alert(\'服务器维护中,此功能暂不开放\');" href="javascript:void(0);" title="用<{tag_name}>帐号登录" class="gray"><i class="<{cls}>"></i><{tag_name}></a></dd>';}else if(t!='renren'){tpls='<dd><a onclick="javascript:weibo.connect(\'<{tag}>\',\'<{from}>\');" href="javascript:void(0);" title="用<{tag_name}>帐号登录" class="gray"><i class="<{cls}>"></i><{tag_name}></a></dd>';}
tpls=tpls.replace(/<\{tag\}>/g,t);tpls=tpls.replace(/<\{from\}>/g,from);tpls=tpls.replace(/<\{tag_name\}>/g,config.setting[t].title);tpls=tpls.replace(/<\{cls\}>/g,config.setting[t].cls);h.push(tpls);}}
h.push('</dl>');return h.join('');},'getHomeIcon':function(){var that=this;return that.getIcon('home');},'getLoginIcon':function(){var that=this;return that.getIcon('login');},'getLoginBoxIcon':function(){var that=this;return that.getIcon('loginbox');},'getRegIcon':function(){var that=this;return that.getIcon('regbox');},'getTiebaIcon':function(){var that=this;return that.getIcon('tiebabox');},'getPhotoIcon':function(){var that=this;return that.getIcon('photobox');},'getDvIcon':function(){var that=this;return that.getIcon('dvbox');},'getUploadIcon':function(){var that=this;var url=that.getUrl('Run');var h=[];if(that.getCookie()){var tpl='<a href="javascript:void(0);" class="<{cls}>" title="用<{tag_name}>帐号登录"><{tag_name}></a>';h.push('<p class="set_sync_info">视频上传并通过审核成功后，将被自动转发到：</p>');h.push('<p class="set_sync_app">');var ck=that.getCookie();for(var t in ck){if(config.setting[t]&&config.setting[t].disp==true&&t!='renren'&&t!='baidu'){var tpls=tpl;tpls=tpls.replace(/<\{tag_name\}>/g,config.setting[t].title);tpls=tpls.replace(/<\{cls\}>/g,config.setting[t].cls);h.push(tpls);}}
h.push('</p>');}else{h.push('<p class="set_sync_info"><a href="'+url+'" target="_blank">开启同步设置</a>,下一次上传视频将会自动转发到：</p>');var tpl='<a href="<{wb_url}>" class="<{cls}>" title="用<{tag_name}>帐号登录" target="_blank"><{tag_name}></a>';h.push('<p class="set_sync_app">');for(var t in config.setting){if(config.setting[t].disp==true&&t!='renren'&&t!='baidu'){var tpls=tpl;tpls=tpls.replace(/<\{wb_url\}>/g,url+t);tpls=tpls.replace(/<\{tag_name\}>/g,config.setting[t].title);tpls=tpls.replace(/<\{cls\}>/g,config.setting[t].cls);h.push(tpls);}}
h.push('</p>');}
return h.join('');},"refresh":function(o,f,t,n){if('home'==f){if(typeof o._h!='undefined'){o._h.HeaderNav('sys_info');o._h.indexLogin('login');}else{o.location.href=o.location.href;}}}};})();